version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    container_name: api-framework
    restart: always
    volumes:
      - api-logs:/usr/src/node-api/logs:rw
    environment:
      - NODE_ENV=development
    depends_on:
      - pgsql
volumes:
  api-logs: null
